update

测试类全部运行失败的原因：

TestBase根据\_testTopic获取autofac容器，如果没有则根据\_testTopic创建，并拿到容器开启一个LifeTimeScope

TestBase.Initial.cs类中的Registerconfiguration方法根据\_testTopic和_databaseName创建对应的application.json，并创建对应的数据库

```EnsureDatabase.For.MySqlDatabase(_connectionString);``` 确保数据库存在，不存在则创建

不是同个fixture中的fact影响，而是其他fixture中的fact方法影响，因为这里不同fixturebase类调用TestBase构造方法时传入了同一个数据库名，而testbase中的dispose方法是按数据库名识别然后遍历所有表进行清理的

总结：不同的fixture不要使用同一个数据库



测试类的ConnectString改成了Charset=utf8;



全部启动测试偶尔出现以下异常

The given key 'xxxx' was not present in the dictionary.

Index was outside the bounds of the array.

System.InvalidOperationException
Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

尝试更换到mysql8.0和最新版本，已知与版本问题无关

debug全部启动不能复现

✅ 降低Dbup-mysql 版本为4.6.0 解决 原版本5.0.44

总结经验，遇到这种偶发性，debug不能复现，而且首先异常追踪定位到第三方代码的，可以尝试降低第三方依赖的版本



team city 仍然在测试这一step卡住，显示测试用例均通过，对比其他人的build log

初步判断是dotCover因为某种原因导致hanging

关闭dotCover 测试通过后能正常生成artifacts

```
/usr/local/TCAgent/tools/JetBrains.dotCover.DotNetCliTool.2021.3.2/macos-x64/dotnet/dotnet exec --runtimeconfig /usr/local/TCAgent/tools/JetBrains.dotCover.DotNetCliTool.2021.3.2/dotCover.unix.runtimeconfig.json /usr/local/TCAgent/tools/JetBrains.dotCover.DotNetCliTool.2021.3.2/dotCover.exe cover /usr/local/TCAgent/temp/agentTmp/1dotCover.xml --ReturnTargetExitCode --AnalyzeTargetArguments=false
```

```
/usr/local/TCAgent/tools/JetBrains.dotCover.DotNetCliTool.2021.3.2/macos-x64/JetBrains.Profiler.PdbServer --stop_request_event=192f19ba365943a4a664865d2bcb41 663ddf35-71ac-4d20-abeb-a6fce40c0a5c
```